### PR TITLE
Preserve placeholder text on focus

### PR DESCRIPTION
**Pull request by mlms13**
This series of commits gives the plugin the option to behave more like the placeholder implementation in Chrome and Firefox.  Placeholder text remains visible until characters are entered into the input. See #92 for more info.

### CODE REVIEW

**Comment by mlms13** [comment]
It should be up-to-date now, but I haven't tested it since merging master into this branch. I'll run it in some browsers on Monday to make sure it still behaves as expected.

**Comment by mauricio-gonzalez** [comment]
@mlms13 Were you able to solve this?

**Comment by mlms13** [comment]
Just fixed a typo that was causing the grunt build to fail. I tested in IE8 and IE9, and as far as I can tell, everything looks ok to me.

**Comment by erikmontes** [comment]
@mlms13 I haven't had time to test it yet, but I do see you use `.on` method to attach an event handler, however according to the jquery docs, `.on()` was [introduced in jQuery 1.7](http://api.jquery.com/on/), the jquery-placeholder plugin itself at this point is compatible with jQuery 1.6 so I don't think it'll work. I'm already thinking for jquery-placeholder 2.0 to drop 1.6 support, but for now it needs to support it.

**Comment by gabskoro** [comment]
Tested on IE11 and nothing, it still disappeares

**Comment by mlms13** [comment]
@gabskoro I don't think the jquery-placeholder plugin polyfills IE11, because it natively supports the `placeholder` attribute. And, unfortunately, its native implementation makes the text disappear on focus. :disappointed:

**Comment by mlms13** [comment]
Looks like my branch is conflicting again. I'm happy to keep it up to date if there's a chance that this will be merged.

**Comment by amerikan** [comment]
@mlms13 yes please update. 

@gabskoro see issue #204, ideally we would want to allow a developer to override native if desired, though still have to figure out how to do that

**Comment by Alex1990** [comment]
If a user pastes some text by the `Paste` command in context menu, the `keydown` or `keyup` events cannot be triggered.

This feature needs an event like `input` event in IE10+ and other modern browers. See this article [A near-perfect oninput shim for IE 8 and 9](http://http://benalpert.com/2013/06/18/a-near-perfect-oninput-shim-for-ie-8-and-9.html). Of course, you can write a simplified version.

**Comment by mlms13** [comment]
@Alex1990 did you mean to open that as a new issue? It doesn't seem related to this PR. Speaking of the PR... one of these days I'll get around to fixing the conflicts.

**Comment by mlms13** [comment]
If anyone is still interested in this feature, [my fork](https://github.com/mlms13/jquery-placeholder/) is up to date with the latest changes. It hasn't been tested recently, and it looks like a weird merge happened with the `setPlaceholder` method. Since I no longer need to support old IE, and there doesn't seem to be interest in merging this upstream, I probably won't continue to keep it up to date, but if anyone else wants to maintain it, it's all yours. :)

**Comment by amerikan** [comment]
@mlms13 I believe this PR got autodeleted because the `master` branch was deleted in favor of the `gh-pages` branch which serves as the project demo. So if you would like to make this changes to the `gh-pages` I can test then merge.

**Comment by mlms13** [comment]
Ah, makes sense. I'll try to fix up the weirdness I'm seeing in the `setPlaceholder` method, and I'll do some testing and reopen against `gh-pages`.

**Pull request closed without merging**
