### PR TITLE
Added npm support. Fixes #243.

### LINKED ISSUE #243: Browserify now requires Bower
https://github.com/mathiasbynens/jquery-placeholder/pull/232

I tried to build my app today and found out it didnt work due to a ```bower install``` as a post-install-script on NPM.

Before I was requiring directly with browserify and worked no issues.

So, whats the deal with this?

### PR DESCRIPTION
**Pull request by callumacrae**
#243

### CODE REVIEW

**Comment by callumacrae** [comment]
@feross: You seem to be pushing the current version on npm from feross/jquery-placeholder: does this all look okay to you?

**Comment by feross** [comment]
Sadly, I think this is unlikely to get merged. See: https://github.com/mathiasbynens/jquery-placeholder/issues/156 and https://github.com/mathiasbynens/jquery-placeholder/pull/158 where I tried in the past.

**Comment by callumacrae** [comment]
Oh no, not one of them. I really hope the developers of this library don't think that anymore, because it's just completely wrong!

http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

And from the _front page_ of npmjs.org:

screen shot 2015-02-18 at 11 12 33
screen shot 2015-02-18 at 11 12 52

By not publishing this library to npm, they're making it difficult or downright impossible (in the case of this library, which breaks when you try to install it from npm) to use browserify.

[jQuery itself is on npm](https://github.com/jquery/jquery/blob/master/package.json). Saying that "npm is for node modules" is completely wrong. Instead I would suggest "I don't want to support browserify".

**Comment by feross** [comment]
The good news is that this library isn't really needed today. [Can I Use](http://caniuse.com/#feat=input-placeholder) says 88.75% of browsers support "placeholder" natively. Unless you need your site to work perfectly in IE8/9.

**Comment by callumacrae** [comment]
I need placeholders all the way down to IE8 on [lostmy.name](https://www.lostmy.name/) :disappointed:

**Comment by callumacrae** [comment]
Guys, I've done all the work for you. You literally just have to merge this pull request and then this library will support browserify.

I see no disadvantage to this. It will make it easier for people to use the library, and it won't make it harder for anyone else!

**Comment by callumacrae** [comment]
:clap: :clap: :clap: :smile:

**Pull request merged**
